# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  gtk_demoapp_config = debug
endif
ifeq ($(config),release)
  gtk_demoapp_config = release
endif

PROJECTS := gtk_demoapp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

gtk_demoapp:
ifneq (,$(gtk_demoapp_config))
	@echo "==== Building gtk_demoapp ($(gtk_demoapp_config)) ===="
	@${MAKE} --no-print-directory -C . -f gtk_demoapp.make config=$(gtk_demoapp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f gtk_demoapp.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   gtk_demoapp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"